### ISSUE TITLE
미디어위키 표와 충돌

### ISSUE THREAD

**Issue by 2DU** [Oriwiki/php-namumark-mediawiki#17]
```
{| class="wikitable"
|-
! 한글 !! 영어 !! 숫자
|-
| ㄱ || A || 1
|-
| ㄴ || B || 2
|-
| ㄷ || C || 3
|}
```

이런 문법이 충돌 납니다.

추.

내용과는 관련 없지만 [파소이드](https://www.mediawiki.org/wiki/Parsoid)란걸 쓰니 미디어위키 속도가 좋아지더라고요 [제타 설명](http://zetawiki.com/wiki/Parsoid)

**Comment by Oriwiki** [comment]
좀 무식한 방법이긴 하지만 마땅히 달리 떠오르지 않아서..;

P.S. 파소이드 직접 해보신 건가요?

**Comment by 2DU** [comment]
P.S. 해 봤는데 속도가 좋아지긴 하더라고요 오리마크랑 충돌 같은 것도 없고

**Comment by Oriwiki** [comment]
설치법 알려주실 수 있으신가요? 아니면 제타위키의 우분투에서의 설치법 그대로 따라하신 건가요?

**Comment by 2DU** [comment]
제타처럼 하고

```
$wgVirtualRestConfig['modules']['parsoid'] = array(  // URL to the Parsoid instance  // Use port 8142 if you use the Debian package  'url' => 'http://localhost:8000',  // Parsoid "domain", see below (optional)  'domain' => 'localhost',  // Parsoid "prefix", see below (optional)  'prefix' => 'localhost' );
```

[여기](https://www.mediawiki.org/wiki/Topic:T4hctrcmfovkstkz)에 나온대로 저걸 넣으면 작동 한다 카더라 하긴 한데... 뭐... [공식 메뉴얼](https://www.mediawiki.org/wiki/Parsoid/Setup)도 있으니 되...겠죠?
