### ISSUE TITLE
tablebordercolor 틀 버그?

### ISSUE THREAD

**Issue by ddarkr** [Oriwiki/php-namumark-mediawiki#22]
||<tablebordercolor=#> || 로 제작된 틀에서 tablebordercolor 는 쏙 빼놓고 렌더링됩니다.

+ 김동동님과 개인적으로 연락할 수 있는 연락처가 있을까요?

**Comment by Oriwiki** [comment]
table bordercolor 해도 적용 안 되나요?

미디어위키가 설치된 서버가 지금 제 수중에 없어서 바로 수정하긴 힘들 것 같습니다. 

`$prop = preg_replace('/^table([^ ])/', 'table $1', $prop);`
머리속으로 예상한다면, php-namumark.php 에 있는 이 정규식 코드가 안 먹는 거 같은데.. tablebordercolor만 안 먹는 거라면 임시 방편으로 이 정규식 코드 위에 이 코드도 추가해보세요. 직접 시험한 것은 아니니깐 꼭 시험용이나 개발용 서버에 일단 적용해보시고 시험해보시길 바랍니다..
`$prop = str_ireplace('tablebordercolor', 'table bordercolor', $prop);`

**Comment by ddarkr** [comment]
적용은 해봤는데 작동은 되지 않네요 ㅠㅠ
나중에 미디어위키 환경이 생기신다면 패치해주세요. 항상 좋은 자료 감사히 사용중입니다
